# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.agents.v1 import agents_pb2 as agents_dot_v1_dot_agents__pb2


class AgentPoolServiceStub:
    """AgentPoolService manages agent lifecycle: spin-up, context hydration,
    handoff, and teardown. It never mediates communication between two
    agent sessions.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpawnSession = channel.unary_unary(
                '/aecp.agents.v1.AgentPoolService/SpawnSession',
                request_serializer=agents_dot_v1_dot_agents__pb2.SpawnSessionRequest.SerializeToString,
                response_deserializer=agents_dot_v1_dot_agents__pb2.SpawnSessionResponse.FromString,
                _registered_method=True)
        self.HydrateContext = channel.unary_unary(
                '/aecp.agents.v1.AgentPoolService/HydrateContext',
                request_serializer=agents_dot_v1_dot_agents__pb2.HydrateContextRequest.SerializeToString,
                response_deserializer=agents_dot_v1_dot_agents__pb2.HydrateContextResponse.FromString,
                _registered_method=True)
        self.HandoffSession = channel.unary_unary(
                '/aecp.agents.v1.AgentPoolService/HandoffSession',
                request_serializer=agents_dot_v1_dot_agents__pb2.HandoffSessionRequest.SerializeToString,
                response_deserializer=agents_dot_v1_dot_agents__pb2.HandoffSessionResponse.FromString,
                _registered_method=True)
        self.TerminateSession = channel.unary_unary(
                '/aecp.agents.v1.AgentPoolService/TerminateSession',
                request_serializer=agents_dot_v1_dot_agents__pb2.TerminateSessionRequest.SerializeToString,
                response_deserializer=agents_dot_v1_dot_agents__pb2.TerminateSessionResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/aecp.agents.v1.AgentPoolService/ListSessions',
                request_serializer=agents_dot_v1_dot_agents__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=agents_dot_v1_dot_agents__pb2.ListSessionsResponse.FromString,
                _registered_method=True)


class AgentPoolServiceServicer:
    """AgentPoolService manages agent lifecycle: spin-up, context hydration,
    handoff, and teardown. It never mediates communication between two
    agent sessions.
    """

    def SpawnSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HydrateContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandoffSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentPoolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpawnSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnSession,
                    request_deserializer=agents_dot_v1_dot_agents__pb2.SpawnSessionRequest.FromString,
                    response_serializer=agents_dot_v1_dot_agents__pb2.SpawnSessionResponse.SerializeToString,
            ),
            'HydrateContext': grpc.unary_unary_rpc_method_handler(
                    servicer.HydrateContext,
                    request_deserializer=agents_dot_v1_dot_agents__pb2.HydrateContextRequest.FromString,
                    response_serializer=agents_dot_v1_dot_agents__pb2.HydrateContextResponse.SerializeToString,
            ),
            'HandoffSession': grpc.unary_unary_rpc_method_handler(
                    servicer.HandoffSession,
                    request_deserializer=agents_dot_v1_dot_agents__pb2.HandoffSessionRequest.FromString,
                    response_serializer=agents_dot_v1_dot_agents__pb2.HandoffSessionResponse.SerializeToString,
            ),
            'TerminateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateSession,
                    request_deserializer=agents_dot_v1_dot_agents__pb2.TerminateSessionRequest.FromString,
                    response_serializer=agents_dot_v1_dot_agents__pb2.TerminateSessionResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=agents_dot_v1_dot_agents__pb2.ListSessionsRequest.FromString,
                    response_serializer=agents_dot_v1_dot_agents__pb2.ListSessionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aecp.agents.v1.AgentPoolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aecp.agents.v1.AgentPoolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentPoolService:
    """AgentPoolService manages agent lifecycle: spin-up, context hydration,
    handoff, and teardown. It never mediates communication between two
    agent sessions.
    """

    @staticmethod
    def SpawnSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.agents.v1.AgentPoolService/SpawnSession',
            agents_dot_v1_dot_agents__pb2.SpawnSessionRequest.SerializeToString,
            agents_dot_v1_dot_agents__pb2.SpawnSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HydrateContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.agents.v1.AgentPoolService/HydrateContext',
            agents_dot_v1_dot_agents__pb2.HydrateContextRequest.SerializeToString,
            agents_dot_v1_dot_agents__pb2.HydrateContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandoffSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.agents.v1.AgentPoolService/HandoffSession',
            agents_dot_v1_dot_agents__pb2.HandoffSessionRequest.SerializeToString,
            agents_dot_v1_dot_agents__pb2.HandoffSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.agents.v1.AgentPoolService/TerminateSession',
            agents_dot_v1_dot_agents__pb2.TerminateSessionRequest.SerializeToString,
            agents_dot_v1_dot_agents__pb2.TerminateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.agents.v1.AgentPoolService/ListSessions',
            agents_dot_v1_dot_agents__pb2.ListSessionsRequest.SerializeToString,
            agents_dot_v1_dot_agents__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
