# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: observability/v1/observability.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'observability/v1/observability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from app.common.v1 import common_pb2 as common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$observability/v1/observability.proto\x12\x15\x61\x65\x63p.observability.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16\x63ommon/v1/common.proto\"K\n\x17RecordAuditEventRequest\x12\x30\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x1a.aecp.common.v1.AuditEventR\x05\x65vent\"5\n\x18RecordAuditEventResponse\x12\x19\n\x08\x65vent_id\x18\x01 \x01(\tR\x07\x65ventId\"\x9e\x01\n\x17QueryAuditEventsRequest\x12\x1b\n\ttenant_id\x18\x01 \x01(\tR\x08tenantId\x12\x30\n\x05since\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x05since\x12\x34\n\x16security_relevant_only\x18\x03 \x01(\x08R\x14securityRelevantOnly\"N\n\x18QueryAuditEventsResponse\x12\x32\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1a.aecp.common.v1.AuditEventR\x06\x65vents2\xf8\x01\n\x0c\x41uditService\x12s\n\x10RecordAuditEvent\x12..aecp.observability.v1.RecordAuditEventRequest\x1a/.aecp.observability.v1.RecordAuditEventResponse\x12s\n\x10QueryAuditEvents\x12..aecp.observability.v1.QueryAuditEventsRequest\x1a/.aecp.observability.v1.QueryAuditEventsResponseB-Z+aecp/proto/observability/v1;observabilityv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'observability.v1.observability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+aecp/proto/observability/v1;observabilityv1'
  _globals['_RECORDAUDITEVENTREQUEST']._serialized_start=120
  _globals['_RECORDAUDITEVENTREQUEST']._serialized_end=195
  _globals['_RECORDAUDITEVENTRESPONSE']._serialized_start=197
  _globals['_RECORDAUDITEVENTRESPONSE']._serialized_end=250
  _globals['_QUERYAUDITEVENTSREQUEST']._serialized_start=253
  _globals['_QUERYAUDITEVENTSREQUEST']._serialized_end=411
  _globals['_QUERYAUDITEVENTSRESPONSE']._serialized_start=413
  _globals['_QUERYAUDITEVENTSRESPONSE']._serialized_end=491
  _globals['_AUDITSERVICE']._serialized_start=494
  _globals['_AUDITSERVICE']._serialized_end=742
# @@protoc_insertion_point(module_scope)
