# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.coordinator.v1 import coordinator_pb2 as coordinator_dot_v1_dot_coordinator__pb2


class CoordinatorServiceStub:
    """CoordinatorService is the only component allowed to make cross-agent
    tradeoffs: scheduling, assignment, and escalation decisions. Agent
    workers never talk to each other directly; everything routes here.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Schedule = channel.unary_unary(
                '/aecp.coordinator.v1.CoordinatorService/Schedule',
                request_serializer=coordinator_dot_v1_dot_coordinator__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=coordinator_dot_v1_dot_coordinator__pb2.ScheduleResponse.FromString,
                _registered_method=True)
        self.Escalate = channel.unary_unary(
                '/aecp.coordinator.v1.CoordinatorService/Escalate',
                request_serializer=coordinator_dot_v1_dot_coordinator__pb2.EscalateRequest.SerializeToString,
                response_deserializer=coordinator_dot_v1_dot_coordinator__pb2.EscalateResponse.FromString,
                _registered_method=True)
        self.ReportBlocker = channel.unary_unary(
                '/aecp.coordinator.v1.CoordinatorService/ReportBlocker',
                request_serializer=coordinator_dot_v1_dot_coordinator__pb2.ReportBlockerRequest.SerializeToString,
                response_deserializer=coordinator_dot_v1_dot_coordinator__pb2.ReportBlockerResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer:
    """CoordinatorService is the only component allowed to make cross-agent
    tradeoffs: scheduling, assignment, and escalation decisions. Agent
    workers never talk to each other directly; everything routes here.
    """

    def Schedule(self, request, context):
        """Schedule evaluates ready task nodes and produces assignment decisions
        for the current tick. Sequencing (what runs in parallel vs. serial)
        is decided here, not by individual agents.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Escalate(self, request, context):
        """Escalate is called by an agent that discovers a task is bigger than
        its granted risk tier. The agent must halt and wait for a decision
        rather than proceeding at its own judgment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportBlocker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.Schedule,
                    request_deserializer=coordinator_dot_v1_dot_coordinator__pb2.ScheduleRequest.FromString,
                    response_serializer=coordinator_dot_v1_dot_coordinator__pb2.ScheduleResponse.SerializeToString,
            ),
            'Escalate': grpc.unary_unary_rpc_method_handler(
                    servicer.Escalate,
                    request_deserializer=coordinator_dot_v1_dot_coordinator__pb2.EscalateRequest.FromString,
                    response_serializer=coordinator_dot_v1_dot_coordinator__pb2.EscalateResponse.SerializeToString,
            ),
            'ReportBlocker': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportBlocker,
                    request_deserializer=coordinator_dot_v1_dot_coordinator__pb2.ReportBlockerRequest.FromString,
                    response_serializer=coordinator_dot_v1_dot_coordinator__pb2.ReportBlockerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aecp.coordinator.v1.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aecp.coordinator.v1.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService:
    """CoordinatorService is the only component allowed to make cross-agent
    tradeoffs: scheduling, assignment, and escalation decisions. Agent
    workers never talk to each other directly; everything routes here.
    """

    @staticmethod
    def Schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.coordinator.v1.CoordinatorService/Schedule',
            coordinator_dot_v1_dot_coordinator__pb2.ScheduleRequest.SerializeToString,
            coordinator_dot_v1_dot_coordinator__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Escalate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.coordinator.v1.CoordinatorService/Escalate',
            coordinator_dot_v1_dot_coordinator__pb2.EscalateRequest.SerializeToString,
            coordinator_dot_v1_dot_coordinator__pb2.EscalateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportBlocker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.coordinator.v1.CoordinatorService/ReportBlocker',
            coordinator_dot_v1_dot_coordinator__pb2.ReportBlockerRequest.SerializeToString,
            coordinator_dot_v1_dot_coordinator__pb2.ReportBlockerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
