# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.taskgraph.v1 import taskgraph_pb2 as taskgraph_dot_v1_dot_taskgraph__pb2


class TaskGraphServiceStub:
    """TaskGraphService owns task decomposition, dependency resolution, and
    ownership boundary bookkeeping. It does not decide assignment or
    sequencing across agents — that is the Coordinator's job.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTaskNode = channel.unary_unary(
                '/aecp.taskgraph.v1.TaskGraphService/CreateTaskNode',
                request_serializer=taskgraph_dot_v1_dot_taskgraph__pb2.CreateTaskNodeRequest.SerializeToString,
                response_deserializer=taskgraph_dot_v1_dot_taskgraph__pb2.CreateTaskNodeResponse.FromString,
                _registered_method=True)
        self.GetTaskNode = channel.unary_unary(
                '/aecp.taskgraph.v1.TaskGraphService/GetTaskNode',
                request_serializer=taskgraph_dot_v1_dot_taskgraph__pb2.GetTaskNodeRequest.SerializeToString,
                response_deserializer=taskgraph_dot_v1_dot_taskgraph__pb2.GetTaskNodeResponse.FromString,
                _registered_method=True)
        self.UpdateTaskStatus = channel.unary_unary(
                '/aecp.taskgraph.v1.TaskGraphService/UpdateTaskStatus',
                request_serializer=taskgraph_dot_v1_dot_taskgraph__pb2.UpdateTaskStatusRequest.SerializeToString,
                response_deserializer=taskgraph_dot_v1_dot_taskgraph__pb2.UpdateTaskStatusResponse.FromString,
                _registered_method=True)
        self.ListReadyTaskNodes = channel.unary_unary(
                '/aecp.taskgraph.v1.TaskGraphService/ListReadyTaskNodes',
                request_serializer=taskgraph_dot_v1_dot_taskgraph__pb2.ListReadyTaskNodesRequest.SerializeToString,
                response_deserializer=taskgraph_dot_v1_dot_taskgraph__pb2.ListReadyTaskNodesResponse.FromString,
                _registered_method=True)
        self.ValidateOwnership = channel.unary_unary(
                '/aecp.taskgraph.v1.TaskGraphService/ValidateOwnership',
                request_serializer=taskgraph_dot_v1_dot_taskgraph__pb2.ValidateOwnershipRequest.SerializeToString,
                response_deserializer=taskgraph_dot_v1_dot_taskgraph__pb2.ValidateOwnershipResponse.FromString,
                _registered_method=True)


class TaskGraphServiceServicer:
    """TaskGraphService owns task decomposition, dependency resolution, and
    ownership boundary bookkeeping. It does not decide assignment or
    sequencing across agents — that is the Coordinator's job.
    """

    def CreateTaskNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReadyTaskNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateOwnership(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskGraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTaskNode': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTaskNode,
                    request_deserializer=taskgraph_dot_v1_dot_taskgraph__pb2.CreateTaskNodeRequest.FromString,
                    response_serializer=taskgraph_dot_v1_dot_taskgraph__pb2.CreateTaskNodeResponse.SerializeToString,
            ),
            'GetTaskNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskNode,
                    request_deserializer=taskgraph_dot_v1_dot_taskgraph__pb2.GetTaskNodeRequest.FromString,
                    response_serializer=taskgraph_dot_v1_dot_taskgraph__pb2.GetTaskNodeResponse.SerializeToString,
            ),
            'UpdateTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTaskStatus,
                    request_deserializer=taskgraph_dot_v1_dot_taskgraph__pb2.UpdateTaskStatusRequest.FromString,
                    response_serializer=taskgraph_dot_v1_dot_taskgraph__pb2.UpdateTaskStatusResponse.SerializeToString,
            ),
            'ListReadyTaskNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReadyTaskNodes,
                    request_deserializer=taskgraph_dot_v1_dot_taskgraph__pb2.ListReadyTaskNodesRequest.FromString,
                    response_serializer=taskgraph_dot_v1_dot_taskgraph__pb2.ListReadyTaskNodesResponse.SerializeToString,
            ),
            'ValidateOwnership': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateOwnership,
                    request_deserializer=taskgraph_dot_v1_dot_taskgraph__pb2.ValidateOwnershipRequest.FromString,
                    response_serializer=taskgraph_dot_v1_dot_taskgraph__pb2.ValidateOwnershipResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aecp.taskgraph.v1.TaskGraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aecp.taskgraph.v1.TaskGraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskGraphService:
    """TaskGraphService owns task decomposition, dependency resolution, and
    ownership boundary bookkeeping. It does not decide assignment or
    sequencing across agents — that is the Coordinator's job.
    """

    @staticmethod
    def CreateTaskNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.taskgraph.v1.TaskGraphService/CreateTaskNode',
            taskgraph_dot_v1_dot_taskgraph__pb2.CreateTaskNodeRequest.SerializeToString,
            taskgraph_dot_v1_dot_taskgraph__pb2.CreateTaskNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.taskgraph.v1.TaskGraphService/GetTaskNode',
            taskgraph_dot_v1_dot_taskgraph__pb2.GetTaskNodeRequest.SerializeToString,
            taskgraph_dot_v1_dot_taskgraph__pb2.GetTaskNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.taskgraph.v1.TaskGraphService/UpdateTaskStatus',
            taskgraph_dot_v1_dot_taskgraph__pb2.UpdateTaskStatusRequest.SerializeToString,
            taskgraph_dot_v1_dot_taskgraph__pb2.UpdateTaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReadyTaskNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.taskgraph.v1.TaskGraphService/ListReadyTaskNodes',
            taskgraph_dot_v1_dot_taskgraph__pb2.ListReadyTaskNodesRequest.SerializeToString,
            taskgraph_dot_v1_dot_taskgraph__pb2.ListReadyTaskNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateOwnership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.taskgraph.v1.TaskGraphService/ValidateOwnership',
            taskgraph_dot_v1_dot_taskgraph__pb2.ValidateOwnershipRequest.SerializeToString,
            taskgraph_dot_v1_dot_taskgraph__pb2.ValidateOwnershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
