# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ommon/v1/common.proto\x12\x0e\x61\x65\x63p.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\",\n\rTenantContext\x12\x1b\n\ttenant_id\x18\x01 \x01(\tR\x08tenantId\"[\n\x11OwnershipBoundary\x12\x1d\n\npath_globs\x18\x01 \x03(\tR\tpathGlobs\x12\'\n\x0f\x66orbidden_globs\x18\x02 \x03(\tR\x0e\x66orbiddenGlobs\"\x9b\x01\n\x05\x41\x63tor\x12.\n\x04kind\x18\x01 \x01(\x0e\x32\x1a.aecp.common.v1.Actor.KindR\x04kind\x12\x0e\n\x02id\x18\x02 \x01(\tR\x02id\"R\n\x04Kind\x12\x14\n\x10KIND_UNSPECIFIED\x10\x00\x12\x0e\n\nKIND_HUMAN\x10\x01\x12\x0e\n\nKIND_AGENT\x10\x02\x12\x14\n\x10KIND_COORDINATOR\x10\x03\"\x8f\x02\n\nAuditEvent\x12\x19\n\x08\x65vent_id\x18\x01 \x01(\tR\x07\x65ventId\x12\x1b\n\ttenant_id\x18\x02 \x01(\tR\x08tenantId\x12+\n\x05\x61\x63tor\x18\x03 \x01(\x0b\x32\x15.aecp.common.v1.ActorR\x05\x61\x63tor\x12\x16\n\x06\x61\x63tion\x18\x04 \x01(\tR\x06\x61\x63tion\x12\x1a\n\x08resource\x18\x05 \x01(\tR\x08resource\x12+\n\x11security_relevant\x18\x06 \x01(\x08R\x10securityRelevant\x12;\n\x0boccurred_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\noccurredAt*\x8b\x01\n\x08RiskTier\x12\x19\n\x15RISK_TIER_UNSPECIFIED\x10\x00\x12\x18\n\x14RISK_TIER_MECHANICAL\x10\x01\x12\x13\n\x0fRISK_TIER_LOCAL\x10\x02\x12\x18\n\x14RISK_TIER_STRUCTURAL\x10\x03\x12\x1b\n\x17RISK_TIER_ARCHITECTURAL\x10\x04*\xf9\x01\n\nTaskStatus\x12\x1b\n\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13TASK_STATUS_PENDING\x10\x01\x12\x17\n\x13TASK_STATUS_BLOCKED\x10\x02\x12\x18\n\x14TASK_STATUS_ASSIGNED\x10\x03\x12\x1b\n\x17TASK_STATUS_IN_PROGRESS\x10\x04\x12\x19\n\x15TASK_STATUS_IN_REVIEW\x10\x05\x12\x19\n\x15TASK_STATUS_ESCALATED\x10\x06\x12\x14\n\x10TASK_STATUS_DONE\x10\x07\x12\x19\n\x15TASK_STATUS_ABANDONED\x10\x08\x42\x1fZ\x1d\x61\x65\x63p/proto/common/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035aecp/proto/common/v1;commonv1'
  _globals['_RISKTIER']._serialized_start=647
  _globals['_RISKTIER']._serialized_end=786
  _globals['_TASKSTATUS']._serialized_start=789
  _globals['_TASKSTATUS']._serialized_end=1038
  _globals['_TENANTCONTEXT']._serialized_start=75
  _globals['_TENANTCONTEXT']._serialized_end=119
  _globals['_OWNERSHIPBOUNDARY']._serialized_start=121
  _globals['_OWNERSHIPBOUNDARY']._serialized_end=212
  _globals['_ACTOR']._serialized_start=215
  _globals['_ACTOR']._serialized_end=370
  _globals['_ACTOR_KIND']._serialized_start=288
  _globals['_ACTOR_KIND']._serialized_end=370
  _globals['_AUDITEVENT']._serialized_start=373
  _globals['_AUDITEVENT']._serialized_end=644
# @@protoc_insertion_point(module_scope)
