# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.integration.v1 import integration_pb2 as integration_dot_v1_dot_integration__pb2


class IntegrationServiceStub:
    """IntegrationService handles what happens when parallel agents produce
    overlapping or contradictory changes. Merge policy is explicit per risk
    tier: some conflicts auto-resolve, some block on a human.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectConflicts = channel.unary_unary(
                '/aecp.integration.v1.IntegrationService/DetectConflicts',
                request_serializer=integration_dot_v1_dot_integration__pb2.DetectConflictsRequest.SerializeToString,
                response_deserializer=integration_dot_v1_dot_integration__pb2.DetectConflictsResponse.FromString,
                _registered_method=True)
        self.ResolveMergePolicy = channel.unary_unary(
                '/aecp.integration.v1.IntegrationService/ResolveMergePolicy',
                request_serializer=integration_dot_v1_dot_integration__pb2.ResolveMergePolicyRequest.SerializeToString,
                response_deserializer=integration_dot_v1_dot_integration__pb2.ResolveMergePolicyResponse.FromString,
                _registered_method=True)
        self.SemanticDiff = channel.unary_unary(
                '/aecp.integration.v1.IntegrationService/SemanticDiff',
                request_serializer=integration_dot_v1_dot_integration__pb2.SemanticDiffRequest.SerializeToString,
                response_deserializer=integration_dot_v1_dot_integration__pb2.SemanticDiffResponse.FromString,
                _registered_method=True)


class IntegrationServiceServicer:
    """IntegrationService handles what happens when parallel agents produce
    overlapping or contradictory changes. Merge policy is explicit per risk
    tier: some conflicts auto-resolve, some block on a human.
    """

    def DetectConflicts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveMergePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticDiff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntegrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectConflicts': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectConflicts,
                    request_deserializer=integration_dot_v1_dot_integration__pb2.DetectConflictsRequest.FromString,
                    response_serializer=integration_dot_v1_dot_integration__pb2.DetectConflictsResponse.SerializeToString,
            ),
            'ResolveMergePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveMergePolicy,
                    request_deserializer=integration_dot_v1_dot_integration__pb2.ResolveMergePolicyRequest.FromString,
                    response_serializer=integration_dot_v1_dot_integration__pb2.ResolveMergePolicyResponse.SerializeToString,
            ),
            'SemanticDiff': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticDiff,
                    request_deserializer=integration_dot_v1_dot_integration__pb2.SemanticDiffRequest.FromString,
                    response_serializer=integration_dot_v1_dot_integration__pb2.SemanticDiffResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aecp.integration.v1.IntegrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aecp.integration.v1.IntegrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntegrationService:
    """IntegrationService handles what happens when parallel agents produce
    overlapping or contradictory changes. Merge policy is explicit per risk
    tier: some conflicts auto-resolve, some block on a human.
    """

    @staticmethod
    def DetectConflicts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.integration.v1.IntegrationService/DetectConflicts',
            integration_dot_v1_dot_integration__pb2.DetectConflictsRequest.SerializeToString,
            integration_dot_v1_dot_integration__pb2.DetectConflictsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveMergePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.integration.v1.IntegrationService/ResolveMergePolicy',
            integration_dot_v1_dot_integration__pb2.ResolveMergePolicyRequest.SerializeToString,
            integration_dot_v1_dot_integration__pb2.ResolveMergePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SemanticDiff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.integration.v1.IntegrationService/SemanticDiff',
            integration_dot_v1_dot_integration__pb2.SemanticDiffRequest.SerializeToString,
            integration_dot_v1_dot_integration__pb2.SemanticDiffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
