# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.state.v1 import state_pb2 as state_dot_v1_dot_state__pb2


class StateServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordDecision = channel.unary_unary(
                '/aecp.state.v1.StateService/RecordDecision',
                request_serializer=state_dot_v1_dot_state__pb2.RecordDecisionRequest.SerializeToString,
                response_deserializer=state_dot_v1_dot_state__pb2.RecordDecisionResponse.FromString,
                _registered_method=True)
        self.GetOwnership = channel.unary_unary(
                '/aecp.state.v1.StateService/GetOwnership',
                request_serializer=state_dot_v1_dot_state__pb2.GetOwnershipRequest.SerializeToString,
                response_deserializer=state_dot_v1_dot_state__pb2.GetOwnershipResponse.FromString,
                _registered_method=True)
        self.GetInterfaceContract = channel.unary_unary(
                '/aecp.state.v1.StateService/GetInterfaceContract',
                request_serializer=state_dot_v1_dot_state__pb2.GetInterfaceContractRequest.SerializeToString,
                response_deserializer=state_dot_v1_dot_state__pb2.GetInterfaceContractResponse.FromString,
                _registered_method=True)
        self.ReportDrift = channel.unary_unary(
                '/aecp.state.v1.StateService/ReportDrift',
                request_serializer=state_dot_v1_dot_state__pb2.ReportDriftRequest.SerializeToString,
                response_deserializer=state_dot_v1_dot_state__pb2.ReportDriftResponse.FromString,
                _registered_method=True)


class StateServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RecordDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOwnership(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterfaceContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportDrift(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordDecision,
                    request_deserializer=state_dot_v1_dot_state__pb2.RecordDecisionRequest.FromString,
                    response_serializer=state_dot_v1_dot_state__pb2.RecordDecisionResponse.SerializeToString,
            ),
            'GetOwnership': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOwnership,
                    request_deserializer=state_dot_v1_dot_state__pb2.GetOwnershipRequest.FromString,
                    response_serializer=state_dot_v1_dot_state__pb2.GetOwnershipResponse.SerializeToString,
            ),
            'GetInterfaceContract': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterfaceContract,
                    request_deserializer=state_dot_v1_dot_state__pb2.GetInterfaceContractRequest.FromString,
                    response_serializer=state_dot_v1_dot_state__pb2.GetInterfaceContractResponse.SerializeToString,
            ),
            'ReportDrift': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportDrift,
                    request_deserializer=state_dot_v1_dot_state__pb2.ReportDriftRequest.FromString,
                    response_serializer=state_dot_v1_dot_state__pb2.ReportDriftResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aecp.state.v1.StateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aecp.state.v1.StateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StateService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecordDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.state.v1.StateService/RecordDecision',
            state_dot_v1_dot_state__pb2.RecordDecisionRequest.SerializeToString,
            state_dot_v1_dot_state__pb2.RecordDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOwnership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.state.v1.StateService/GetOwnership',
            state_dot_v1_dot_state__pb2.GetOwnershipRequest.SerializeToString,
            state_dot_v1_dot_state__pb2.GetOwnershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInterfaceContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.state.v1.StateService/GetInterfaceContract',
            state_dot_v1_dot_state__pb2.GetInterfaceContractRequest.SerializeToString,
            state_dot_v1_dot_state__pb2.GetInterfaceContractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportDrift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.state.v1.StateService/ReportDrift',
            state_dot_v1_dot_state__pb2.ReportDriftRequest.SerializeToString,
            state_dot_v1_dot_state__pb2.ReportDriftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
