# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.observability.v1 import observability_pb2 as observability_dot_v1_dot_observability__pb2


class AuditServiceStub:
    """AuditService is the single write path for the escalation audit trail.
    Every other service calls RecordAuditEvent instead of writing to its
    own log for anything security-relevant or Tier 2+.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordAuditEvent = channel.unary_unary(
                '/aecp.observability.v1.AuditService/RecordAuditEvent',
                request_serializer=observability_dot_v1_dot_observability__pb2.RecordAuditEventRequest.SerializeToString,
                response_deserializer=observability_dot_v1_dot_observability__pb2.RecordAuditEventResponse.FromString,
                _registered_method=True)
        self.QueryAuditEvents = channel.unary_unary(
                '/aecp.observability.v1.AuditService/QueryAuditEvents',
                request_serializer=observability_dot_v1_dot_observability__pb2.QueryAuditEventsRequest.SerializeToString,
                response_deserializer=observability_dot_v1_dot_observability__pb2.QueryAuditEventsResponse.FromString,
                _registered_method=True)


class AuditServiceServicer:
    """AuditService is the single write path for the escalation audit trail.
    Every other service calls RecordAuditEvent instead of writing to its
    own log for anything security-relevant or Tier 2+.
    """

    def RecordAuditEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAuditEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordAuditEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordAuditEvent,
                    request_deserializer=observability_dot_v1_dot_observability__pb2.RecordAuditEventRequest.FromString,
                    response_serializer=observability_dot_v1_dot_observability__pb2.RecordAuditEventResponse.SerializeToString,
            ),
            'QueryAuditEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAuditEvents,
                    request_deserializer=observability_dot_v1_dot_observability__pb2.QueryAuditEventsRequest.FromString,
                    response_serializer=observability_dot_v1_dot_observability__pb2.QueryAuditEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aecp.observability.v1.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aecp.observability.v1.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService:
    """AuditService is the single write path for the escalation audit trail.
    Every other service calls RecordAuditEvent instead of writing to its
    own log for anything security-relevant or Tier 2+.
    """

    @staticmethod
    def RecordAuditEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.observability.v1.AuditService/RecordAuditEvent',
            observability_dot_v1_dot_observability__pb2.RecordAuditEventRequest.SerializeToString,
            observability_dot_v1_dot_observability__pb2.RecordAuditEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAuditEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aecp.observability.v1.AuditService/QueryAuditEvents',
            observability_dot_v1_dot_observability__pb2.QueryAuditEventsRequest.SerializeToString,
            observability_dot_v1_dot_observability__pb2.QueryAuditEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
